"""Initial schema

Revision ID: 280838405dcc
Revises: 
Create Date: 2026-09-18 09:17:28.730784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '280838405dcc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chave_acesso', sa.String(length=44), nullable=True))
        batch_op.add_column(sa.Column('valor_total', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cnpj_emitente', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('score_confianca', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dados_extraidos_json', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documentos_chave_acesso'), ['chave_acesso'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_chave_acesso'))
        batch_op.drop_column('dados_extraidos_json')
        batch_op.drop_column('score_confianca')
        batch_op.drop_column('cnpj_emitente')
        batch_op.drop_column('valor_total')
        batch_op.drop_column('chave_acesso')

    # ### end Alembic commands ###
